# Generated by Django 3.2 on 2023-07-27 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_auto_20230724_2144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'permissions': [('HAS_Transaction_permission', 'user has Transaction permission')]},
        ),
    ]
